#!/usr/bin/env python3
"""
Comprehensive Tournament Validation Tests

This module contains tests to validate the correctness and reliability of
tournament evaluation results. These tests ensure we can trust the
experimental data generated by the tournament system.
"""

import sys
import tempfile
import csv
from pathlib import Path
from unittest.mock import patch, MagicMock

import jax
import pytest
import numpy as np

# Add baselines to path for local testing
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from baselines.run_tournament import (
    TournamentEvaluator, TournamentPlayer, TournamentMatch
)


class TestTournamentValidation:
    """Test suite for tournament validation."""

    def setup_method(self):
        """Set up test environment."""
        self.temp_dir = tempfile.mkdtemp()
        self.evaluator = TournamentEvaluator(
            env_name="MPE_simple_sumo_v3",
            episodes_per_matchup=20,  # Small for testing
            output_dir=self.temp_dir,
            max_episode_steps=50
        )

    def test_scripted_player_determinism(self):
        """Test that scripted players produce deterministic results."""
        # Create identical players
        player1 = TournamentPlayer(name="scripted_noop", player_type="scripted")
        player2 = TournamentPlayer(name="scripted_noop", player_type="scripted")
        
        # Run multiple episodes with same seed
        rng_key = jax.random.PRNGKey(42)
        results = []
        
        for i in range(5):
            result = self.evaluator._run_episode_with_positions(
                green_player=player1,
                red_player=player2,
                rng_key=rng_key,
                episode_id=i,
                side=1,
                match_id="test"
            )
            results.append(result)
        
        # All results should be identical (deterministic)
        first_result = results[0]
        for result in results[1:]:
            assert result['winner'] == first_result['winner']
            assert result['green_reward'] == first_result['green_reward']
            assert result['red_reward'] == first_result['red_reward']
            assert result['episode_length'] == first_result['episode_length']

    def test_side_flip_symmetry(self):
        """Test that side-flipping produces correct symmetrical results."""
        player1 = TournamentPlayer(name="scripted_seek", player_type="scripted")
        player2 = TournamentPlayer(name="scripted_noop", player_type="scripted")
        
        rng_key = jax.random.PRNGKey(42)
        
        # Side 1: player1 (green) vs player2 (red)
        rng_key1, rng_key2 = jax.random.split(rng_key)
        result1 = self.evaluator._run_episode_with_positions(
            green_player=player1,
            red_player=player2,
            rng_key=rng_key1,
            episode_id=1,
            side=1,
            match_id="test"
        )
        
        # Side 2: player2 (green) vs player1 (red)
        result2 = self.evaluator._run_episode_with_positions(
            green_player=player2,
            red_player=player1,
            rng_key=rng_key2,
            episode_id=2,
            side=2,
            match_id="test"
        )
        
        # Verify side assignments are correct
        assert result1['green_player'] == player1.name
        assert result1['red_player'] == player2.name
        assert result2['green_player'] == player2.name
        assert result2['red_player'] == player1.name
        
        # If player1 wins in side 1, they should win in side 2 too
        # (assuming deterministic behavior)
        if result1['winner'] == player1.name:
            assert result2['winner'] == player1.name
        elif result1['winner'] == player2.name:
            assert result2['winner'] == player2.name

    def test_reward_consistency(self):
        """Test that rewards are consistent with winner determination."""
        player1 = TournamentPlayer(name="scripted_seek", player_type="scripted")
        player2 = TournamentPlayer(name="scripted_noop", player_type="scripted")
        
        rng_key = jax.random.PRNGKey(42)
        result = self.evaluator._run_episode_with_positions(
            green_player=player1,
            red_player=player2,
            rng_key=rng_key,
            episode_id=1,
            side=1,
            match_id="test"
        )
        
        # Winner should have higher or equal reward
        if result['winner'] == result['green_player']:
            assert result['green_reward'] >= result['red_reward']
        elif result['winner'] == result['red_player']:
            assert result['red_reward'] >= result['green_reward']
        else:  # Draw
            assert result['green_reward'] == result['red_reward']

    def test_csv_output_format(self):
        """Test that CSV output has correct format and data."""
        # Create test players
        players = [
            TournamentPlayer(name="scripted_seek", player_type="scripted"),
            TournamentPlayer(name="scripted_noop", player_type="scripted")
        ]
        
        self.evaluator.players = players
        self.evaluator.setup_matches()
        
        # Run a small tournament
        rng_key = jax.random.PRNGKey(42)
        self.evaluator.run_tournament(rng_key)
        
        # Check CSV file exists and has correct format
        csv_file = self.evaluator.output_dir / "tournament_results.csv"
        assert csv_file.exists()
        
        with open(csv_file, 'r') as f:
            reader = csv.DictReader(f)
            rows = list(reader)
            
            # Check required columns exist
            required_columns = [
                'match_id', 'episode_id', 'player1', 'player2',
                'green_player', 'red_player', 'winner',
                'player1_reward', 'player2_reward',
                'green_reward', 'red_reward', 'episode_length', 'side'
            ]
            
            for col in required_columns:
                assert col in reader.fieldnames, f"Missing column: {col}"
            
            # Check data consistency
            for row in rows:
                # Winner should be one of the players or 'draw'
                assert row['winner'] in [row['player1'], row['player2'], 'draw']
                
                # Side should be 1 or 2
                assert row['side'] in ['1', '2']
                
                # Episode length should be positive
                assert int(row['episode_length']) > 0
                
                # Rewards should be numeric
                float(row['player1_reward'])
                float(row['player2_reward'])
                float(row['green_reward'])
                float(row['red_reward'])

    def test_match_completeness(self):
        """Test that all matches are completed with correct episode counts."""
        players = [
            TournamentPlayer(name="scripted_seek", player_type="scripted"),
            TournamentPlayer(name="scripted_noop", player_type="scripted"),
            TournamentPlayer(name="scripted_random", player_type="scripted")
        ]
        
        self.evaluator.players = players
        self.evaluator.setup_matches()
        
        # Run tournament
        rng_key = jax.random.PRNGKey(42)
        self.evaluator.run_tournament(rng_key)
        
        # Check that we have the right number of matches
        expected_matches = len(players) * (len(players) - 1)  # Round-robin
        assert len(self.evaluator.matches) == expected_matches
        
        # Check that each match has the right number of episodes
        expected_episodes_per_match = self.evaluator.episodes_per_matchup
        
        match_episode_counts = {}
        for result in self.evaluator.results:
            match_id = result['match_id']
            match_episode_counts[match_id] = match_episode_counts.get(match_id, 0) + 1
        
        for match_id, count in match_episode_counts.items():
            assert count == expected_episodes_per_match, \
                f"Match {match_id} has {count} episodes, expected {expected_episodes_per_match}"

    def test_scripted_behavior_discovery(self):
        """Test that scripted behaviors are discovered correctly."""
        scripted_players = self.evaluator.create_scripted_players()
        
        # Should have at least the basic scripted behaviors
        player_names = [p.name for p in scripted_players]
        
        # Check that all players have correct naming format
        for name in player_names:
            assert name.startswith("scripted_")
            behavior = name.replace("scripted_", "")
            assert len(behavior) > 0

    def test_tournament_reproducibility(self):
        """Test that tournaments are reproducible with same seed."""
        players = [
            TournamentPlayer(name="scripted_seek", player_type="scripted"),
            TournamentPlayer(name="scripted_noop", player_type="scripted")
        ]
        
        # Run tournament twice with same seed
        results1 = self._run_mini_tournament(players, seed=42)
        results2 = self._run_mini_tournament(players, seed=42)
        
        # Results should be identical
        assert len(results1) == len(results2)
        for r1, r2 in zip(results1, results2):
            assert r1['winner'] == r2['winner']
            assert r1['green_reward'] == r2['green_reward']
            assert r1['red_reward'] == r2['red_reward']
            assert r1['episode_length'] == r2['episode_length']

    def test_different_seeds_produce_variation(self):
        """Test that different seeds produce different results."""
        players = [
            TournamentPlayer(name="scripted_random", player_type="scripted"),
            TournamentPlayer(name="scripted_noop", player_type="scripted")
        ]
        
        # Run tournament with different seeds
        results1 = self._run_mini_tournament(players, seed=42)
        results2 = self._run_mini_tournament(players, seed=123)
        
        # At least some results should be different (due to randomness)
        differences = 0
        for r1, r2 in zip(results1, results2):
            if (r1['winner'] != r2['winner'] or 
                r1['episode_length'] != r2['episode_length']):
                differences += 1
        
        # With random behavior, we expect some variation
        assert differences > 0, "No variation found between different seeds"

    def _run_mini_tournament(self, players, seed):
        """Helper method to run a small tournament."""
        evaluator = TournamentEvaluator(
            env_name="MPE_simple_sumo_v3",
            episodes_per_matchup=4,  # Very small for testing
            output_dir=tempfile.mkdtemp(),
            max_episode_steps=20
        )
        
        evaluator.players = players
        evaluator.setup_matches()
        
        rng_key = jax.random.PRNGKey(seed)
        evaluator.run_tournament(rng_key)
        
        return evaluator.results


class TestResultAnalysis:
    """Test suite for result analysis and validation."""

    def test_win_rate_calculation(self):
        """Test that win rates are calculated correctly."""
        # Mock results data
        mock_results = [
            {'player1': 'A', 'player2': 'B', 'winner': 'A'},
            {'player1': 'A', 'player2': 'B', 'winner': 'A'},
            {'player1': 'A', 'player2': 'B', 'winner': 'B'},
            {'player1': 'A', 'player2': 'B', 'winner': 'draw'},
        ]
        
        # Calculate win rates manually
        player_stats = {'A': {'wins': 0, 'losses': 0, 'draws': 0, 'episodes': 0},
                       'B': {'wins': 0, 'losses': 0, 'draws': 0, 'episodes': 0}}
        
        for result in mock_results:
            p1, p2 = result['player1'], result['player2']
            player_stats[p1]['episodes'] += 1
            player_stats[p2]['episodes'] += 1
            
            if result['winner'] == p1:
                player_stats[p1]['wins'] += 1
                player_stats[p2]['losses'] += 1
            elif result['winner'] == p2:
                player_stats[p2]['wins'] += 1
                player_stats[p1]['losses'] += 1
            else:
                player_stats[p1]['draws'] += 1
                player_stats[p2]['draws'] += 1
        
        # Verify calculations
        assert player_stats['A']['wins'] == 2
        assert player_stats['A']['losses'] == 1
        assert player_stats['A']['draws'] == 1
        assert player_stats['B']['wins'] == 1
        assert player_stats['B']['losses'] == 2
        assert player_stats['B']['draws'] == 1

    def test_summary_generation(self):
        """Test that tournament summary is generated correctly."""
        temp_dir = tempfile.mkdtemp()
        evaluator = TournamentEvaluator(
            env_name="MPE_simple_sumo_v3",
            episodes_per_matchup=4,
            output_dir=temp_dir
        )
        
        # Mock some results
        evaluator.results = [
            {
                'player1': 'scripted_seek', 'player2': 'scripted_noop',
                'winner': 'scripted_seek', 'player1_reward': 1.0, 'player2_reward': 0.0
            },
            {
                'player1': 'scripted_seek', 'player2': 'scripted_noop',
                'winner': 'scripted_seek', 'player1_reward': 1.0, 'player2_reward': 0.0
            }
        ]
        
        evaluator.generate_summary()
        
        # Check that summary file exists
        summary_file = Path(temp_dir) / f"run_{evaluator.run_timestamp}" / "tournament_summary.txt"
        assert summary_file.exists()
        
        # Check summary content
        with open(summary_file, 'r') as f:
            content = f.read()
            assert "TOURNAMENT SUMMARY" in content
            assert "scripted_seek" in content
            assert "scripted_noop" in content


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
